namespace Aweton.Labs.CurrencyRates.Cli.CbrXml;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ValCurs
{

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute("Valute")]
  public ValCursValute[] Valute { get; set; } = null!;

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string Date { get; set; } = null!;

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string name { get; set; } = null!;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ValCursValute
{

  /// <remarks/>
  public ushort NumCode { get; set; }

  /// <remarks/>
  public string CharCode { get; set; } = null!;

  /// <remarks/>
  public uint Nominal { get; set; }

  /// <remarks/>
  public string Name { get; set; } = null!;

  /// <remarks/>
  public string Value { get; set; } = null!;

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string ID { get; set; } = null!;
}
