namespace Aweton.Labs.CurrencyRates.Cli.CbrXml;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ValCurs {
    
    private ValCursValute[] valuteField = null!;
    
    private string dateField = null!;
    
    private string nameField = null!;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Valute")]
    public ValCursValute[] Valute {
        get {
            return this.valuteField;
        }
        set {
            this.valuteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ValCursValute {
    
    private ushort numCodeField;
    
    private string charCodeField = null!;
    
    private uint nominalField;
    
    private string nameField = null!;
    
    private string valueField = null!;
    
    private string idField = null!;
    
    /// <remarks/>
    public ushort NumCode {
        get {
            return this.numCodeField;
        }
        set {
            this.numCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CharCode {
        get {
            return this.charCodeField;
        }
        set {
            this.charCodeField = value;
        }
    }
    
    /// <remarks/>
    public uint Nominal {
        get {
            return this.nominalField;
        }
        set {
            this.nominalField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
